### ISSUE TITLE
Final setup failure

### ISSUE THREAD

**Issue by CockneyUSA78260** [linuxkidd/ev4rv#2]
Hi.  I've just finished all the steps for this project.  Everything works except the control and monitoring of the OpenEVSE.  The EV4RV sees the the emon unit and shows the current/voltage usage.  The OpenEVSE shows connected to the EV4RV but nothing shows in the UI. The OpenEVSE shows connected to the WiFi and shows these statistics: IP Address:
XX.XX.XX.XX
Successful packets:
0 of 4
OpenEVSE
RAPI packets:
3297 of 3297.

What should I try to fix this?

Alan

**Comment by linuxkidd** [comment]
Hello Alan,
  Please confirm you have setup the OpenEVSE unit to connect to the EV4RV MQTT server per the following:
https://github.com/linuxkidd/ev4rv/wiki/OpenEVSE-Initial-Configuration#setup-mqtt

Let me know if that helps.
LK

**Comment by CockneyUSA78260** [comment]
I followed this page during the setup.  These are the screen captures.

 

 

Alan

**Comment by CockneyUSA78260** [comment]
Can you see them in the email?  
![image](https://user-images.githubusercontent.com/63086367/78323063-4b494c00-7536-11ea-9edc-d825a4381b53.png)

**Comment by CockneyUSA78260** [comment]
![image](https://user-images.githubusercontent.com/63086367/78323040-38cf1280-7536-11ea-84c6-add75ca896b1.png)

**Comment by linuxkidd** [comment]
Does the MQTT panel on the Services tab of the OpenEVSE say it is connected?

**Comment by CockneyUSA78260** [comment]
Yes.  
![image](https://user-images.githubusercontent.com/63086367/78323110-7895fa00-7536-11ea-9e9a-5f0f1bdf8359.png)

**Comment by CockneyUSA78260** [comment]
This is the firmware level of the OpenEVSE..
![image](https://user-images.githubusercontent.com/63086367/78323151-97948c00-7536-11ea-9e0f-6181e49a9a45.png)

**Comment by linuxkidd** [comment]
Ah, thanks, the screenshots did now show up.   The setup looks complete at this point.   Can you test changing one of your settings ( trip margin to 15 for example ).. that should force an update message for the OpenEVSE, then we can see if the EVSE replies.

**Comment by CockneyUSA78260** [comment]
The EV4RV does not seem to be controlling the EVSE at all.  The EV4RV is showing an EVSE limit of 32A but the EVSE is still charging at 40A. I did change the trip margin to 15 but nothing changed.

**Comment by linuxkidd** [comment]
Hi Alan,
  One other thing.. I see your firmware is 3.0.2.  OpenEVSE has released 3.0.3 which fixes an MQTT issue.  You can download and apply the 'firmware.bin' file from here: 
https://github.com/OpenEVSE/ESP32_WiFi_V3.x/releases

Let me know if that helps.
LK

**Comment by CockneyUSA78260** [comment]
Do I just download the firmware.bin?

**Comment by linuxkidd** [comment]
Yes, only the firmware.bin for updating via the OpenEVSE web interface (where your earlier screenshot was taken).

**Comment by CockneyUSA78260** [comment]
Yup.  That seems to have been the issue.  All working now.  Thank you so much for your assistance.

**Comment by linuxkidd** [comment]
Excellent!  You are most welcome.  Great to hear you got it all built and working.
